### PR TITLE
Setup Asciidoctor

### PR DESCRIPTION
**Pull request by TruongQuangSB**
- Setup Asciidoctor over custom action

### CODE REVIEW

**Comment by PetersNils** [comment]
I think we should stick with using github actions for this. They're practically instantanious (0-1 seconds) while pulling a docker image will take some time.

Instead, we could combine the two actions and the installation of asciidoctor into one custom action that can easily be reused.

**Review by PetersNils — CHANGES_REQUESTED** [review]
I think we should stick with using github actions for this. They're practically instantanious (0-1 seconds) while pulling a docker image will take some time.

Instead, we could combine the two actions and the installation of asciidoctor into one custom action that can easily be reused.

**Comment by TruongQuangSB** [comment]
> I think we should stick with using github actions for this. They're practically instantanious (0-1 seconds) while pulling a docker image will take some time.
> 
> Instead, we could combine the two actions and the installation of asciidoctor into one custom action that can easily be reused.

you are right, i have change to use custom github actions ([setup-asciidoctor](https://github.com/eclipse-set/build/blob/main/.github/actions/setup-asciidoctor/action.yml)

**Review by pstuecker — APPROVED** [review]

**Review by PetersNils — APPROVED** [review]

**Comment by TruongQuangSB** [comment]
# Table difference view: UGBB - Ssks
 | Row   | A                  | B              | C                      | D                  | E                    | F                                                                                     | G                                  | H                        | I                    | J                                       | K                                       | L                       | M                       | N                       | O                         | P                         | Q                                     | R                                          | S                                        | T                                     | U                                     | V                                        | W                                     | X                                   | Y                                   | Z                                                         | AA                                                   | AB                                                 | AC                                                 | AD                                                 | AE                                                 | AF                                                 | AG                                                              | AH                                                              | AI                                                              | AJ                                                              | AK                                                              | AL                                                              | AM                                                              | AN                                                             | AO                                                 | AP                                                                                      | AQ                                                                   | AR                                                           | AS                                                             | AT                                                             | AU                                                               | AV                                                         | AW                                                         | AX                                                         |
|-------|--------------------|----------------|------------------------|--------------------|----------------------|---------------------------------------------------------------------------------------|------------------------------------|--------------------------|----------------------|-----------------------------------------|-----------------------------------------|-------------------------|-------------------------|-------------------------|---------------------------|---------------------------|---------------------------------------|--------------------------------------------|------------------------------------------|---------------------------------------|---------------------------------------|------------------------------------------|---------------------------------------|-------------------------------------|-------------------------------------|-----------------------------------------------------------|------------------------------------------------------|----------------------------------------------------|----------------------------------------------------|----------------------------------------------------|----------------------------------------------------|----------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------|----------------------------------------------------------------|----------------------------------------------------|-----------------------------------------------------------------------------------------|----------------------------------------------------------------------|--------------------------------------------------------------|----------------------------------------------------------------|----------------------------------------------------------------|------------------------------------------------------------------|------------------------------------------------------------|------------------------------------------------------------|------------------------------------------------------------|
|       | Bezeichnung Signal | Signal-Art​    | Signal-Art​            | Signal-Art​        | Standortmerkmale​​​​ | Standortmerkmale​​​​                                                                  | Standortmerkmale​​​​               | Standortmerkmale​​​​     | Standortmerkmale​​​​ | Standortmerkmale​​​​                    | Standortmerkmale​​​​                    | Standortmerkmale​​​​    | Standortmerkmale​​​​    | Standortmerkmale​​​​    | Standortmerkmale​​​​      | Standortmerkmale​​​​      | Konstruktive Merkmale​​​​​​​​​​​​​​​​ | Konstruktive Merkmale​​​​​​​​​​​​​​​​      | Konstruktive Merkmale​​​​​​​​​​​​​​​​    | Konstruktive Merkmale​​​​​​​​​​​​​​​​ | Konstruktive Merkmale​​​​​​​​​​​​​​​​ | Konstruktive Merkmale​​​​​​​​​​​​​​​​    | Konstruktive Merkmale​​​​​​​​​​​​​​​​ | Anschluss​​​​​​​​​​​​​​​​​​​​​​​    | Anschluss​​​​​​​​​​​​​​​​​​​​​​​    | Anschluss​​​​​​​​​​​​​​​​​​​​​​​                          | Anschluss​​​​​​​​​​​​​​​​​​​​​​​                     | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                       | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                      | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Signalisierung​​​​​​​​​​​​​​​​​​​​​​​​​​​                                               | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                  | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​            | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​            | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​              | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​        | Sonstiges​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​        | Bemerkung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ |
|       | Bezeichnung Signal | Signal-Art​    | Signal-Art​            | Signal-Art​        | Standort​​​​         | Standort​​​​                                                                          | Sonstige zulässige Anordnung​​​​​​ | Lichtraum- profil​​​​​​​ | Über- höhung​​​​​​​​ | Abstand Mastmitte - Gleismitte​​​​​​​​​ | Abstand Mastmitte - Gleismitte​​​​​​​​​ | Sichtbarkeit​​​​​​​​​​​ | Sichtbarkeit​​​​​​​​​​​ | Sichtbarkeit​​​​​​​​​​​ | Ausrichtung​​​​​​​​​​​​​​ | Ausrichtung​​​​​​​​​​​​​​ | Anordnung​​​​​​​​​​​​​​​​             | Anordnung​​​​​​​​​​​​​​​​                  | Obere Lichtpunkt- höhe​​​​​​​​​​​​​​​​​​ | Streuscheibe​​​​​​​​​​​​​​​​​​​       | Streuscheibe​​​​​​​​​​​​​​​​​​​       | Fundament​​​​​​​​​​​​​​​​​​​​​           | Fundament​​​​​​​​​​​​​​​​​​​​​        | Schaltkasten​​​​​​​​​​​​​​​​​​​​​​​ | Schaltkasten​​​​​​​​​​​​​​​​​​​​​​​ | Separater Schaltkasten Steuerung​​​​​​​​​​​​​​​​​​​​​​​​​ | Dauerhaft Nacht- schaltung​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Schirm)​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Schirm)​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Schirm)​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Schirm)​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Schirm)​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Signalbegriffe (Zusatzanzeiger)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Nach- geordnetes Signal​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Mastschild​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Weitere (z. B. ETCS-Halttafel, Vorsignaltafel)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Automatische Fahrtstellung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Dunkel- schaltung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Durchfahrt erlaubt​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Besetzte Ausfahrt​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Löschung Zs 1/Zs 7​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Überwachung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Überwachung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Bemerkung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ |
|       | Bezeichnung Signal | Reales Signal​ | Funktion ohne Signal​​ | Fiktives Signal​​​ | Strecke​​​​          | km​​​​​                                                                               | Sonstige zulässige Anordnung​​​​​​ | Lichtraum- profil​​​​​​​ | Über- höhung​​​​​​​​ | Links​​​​​​​​​                          | Rechts​​​​​​​​​​                        | Soll​​​​​​​​​​​         | Mindest​​​​​​​​​​​​     | Ist​​​​​​​​​​​​​        | Entfernung​​​​​​​​​​​​​​  | Richtpunkt​​​​​​​​​​​​​​​ | Befestigung​​​​​​​​​​​​​​​​           | Regelzeichnung Nr. (Bild)​​​​​​​​​​​​​​​​​ | Obere Lichtpunkt- höhe​​​​​​​​​​​​​​​​​​ | Art​​​​​​​​​​​​​​​​​​​                | Stellung​​​​​​​​​​​​​​​​​​​​          | Art/ Rz. Nr. (Bild)​​​​​​​​​​​​​​​​​​​​​ | Höhe u. SO​​​​​​​​​​​​​​​​​​​​​​      | Bezeichnung​​​​​​​​​​​​​​​​​​​​​​​  | Entfernung​​​​​​​​​​​​​​​​​​​​​​​​  | Bezeichnung​​​​​​​​​​​​​​​​​​​​​​​​​                      | Dauerhaft Nacht- schaltung​​​​​​​​​​​​​​​​​​​​​​​​​​ | Hp, (Hl)​​​​​​​​​​​​​​​​​​​​​​​​​​​                | Ks, (Vr)​​​​​​​​​​​​​​​​​​​​​​​​​​​​               | Zl, Kl​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                | Ra 12/ Sh 1​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​          | Zs​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                  | Zs 2​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                            | Zs 2v​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                          | Zs 3​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                          | Zs 3v​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                        | Zs​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                          | Zp​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                         | Kombination​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​               | Nach- geordnetes Signal​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Mastschild​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Regelzeichnung Nr. (Bild)​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​                      | Automatische Fahrtstellung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Dunkel- schaltung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Durchfahrt erlaubt​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Besetzte Ausfahrt​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Löschung Zs 1/Zs 7​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ | Zs 2​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​        | Zs 2v​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​      | Bemerkung​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​ |
|       |                    |                |                        |                    |                      |                                                                                       |                                    |                          | mm                   | mm                                      | mm                                      | m                       | m                       | m                       | m                         |                           |                                       |                                            | mm                                       |                                       |                                       |                                          | mm                                    |                                     | m                                   |                                                           |                                                      |                                                    |                                                    |                                                    |                                                    |                                                    |                                                                 |                                                                 |                                                                 |                                                                 |                                                                 |                                                                 |                                                                 |                                                                |                                                    |                                                                                         |                                                                      |                                                              |                                                                |                                                                |                                                                  |                                                            |                                                            |                                                            |
| 3     | 63105              |                |                        |                    | 5919                 | ${\color{gold}198,724  <br>~~198,787~~}$ <br> ${\color{red}198,800  <br>~~198,787~~}$ |                                    |                          | 12  <br>~~33~~       |                                         |                                         |                         |                         |                         |                           |                           | OL-​Mast                              | S ​543.1.1 ​(6)​                           |                                          |                                       |                                       |                                          |                                       |                                     |                                     |                                                           |                                                      |                                                    |                                                    |                                                    |                                                    |                                                    |                                                                 |                                                                 |                                                                 |                                                                 |                                                                 |                                                                 |                                                                 |                                                                |                                                    |                                                                                         |                                                                      |                                                              |                                                                |                                                                |                                                                  |                                                            |                                                            | *2, ~~*1~~                                                 |

**Comment by TruongQuangSB** [comment]
# Table difference view: UGBB - Plaz_model
 | Lfd. Nr.           | Schweregrad           | Problemart                                                                               | Zeilennummer    | Objektart                | Attribut/-gruppe                                                                | Bereich                  | Zustand         | Meldung                                                                                                                                                                                                  |
|--------------------|-----------------------|------------------------------------------------------------------------------------------|-----------------|--------------------------|---------------------------------------------------------------------------------|--------------------------|-----------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1                  | Fehler                | Bearbeitungsvermerk                                                                      | 193             | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 2                  | Fehler                | Bearbeitungsvermerk                                                                      | 257             | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 3                  | Fehler                | Bearbeitungsvermerk                                                                      | 353             | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 4                  | Fehler                | Bearbeitungsvermerk                                                                      | 401             | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 5                  | Fehler                | Bearbeitungsvermerk                                                                      | 616             | Aussenelementansteuerung | ${\color{gold}AEA_Allg}$ <br> ${\color{red}Aussenelementansteuerung_Art}$       | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 6                  | Fehler                | Bearbeitungsvermerk                                                                      | 1116            | Bedien_Anzeige_Element   | ${\color{gold}Bedien_Anzeige_Element_Allg}$ <br> ${\color{red}Taste}$           | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 7                  | Fehler                | Bearbeitungsvermerk                                                                      | 1188            | Bedien_Anzeige_Element   | ${\color{gold}Bedien_Anzeige_Element_Allg}$ <br> ${\color{red}Taste}$           | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 8                  | Fehler                | Bearbeitungsvermerk                                                                      | 1289            | Bedien_Anzeige_Element   | ${\color{gold}Bedien_Anzeige_Element_Allg}$ <br> ${\color{red}Taste}$           | Betrachtung              | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 9                  | Fehler                | Bearbeitungsvermerk                                                                      | 55286           | PZB_Element_Zuordnung    | ${\color{gold}PZB_Element_Zuordnung_Fstr}$ <br> ${\color{red}Wirksamkeit_Fstr}$ | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 10                 | Fehler                | Bearbeitungsvermerk                                                                      | 56082           | PZB_Element_Zuordnung    | ${\color{gold}PZB_Element_Zuordnung_Fstr}$ <br> ${\color{red}Wirksamkeit_Fstr}$ | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 15                 | Fehler                | Bearbeitungsvermerk                                                                      | 58232           | Schloss                  | ${\color{gold}Schloss_W}$ <br> ${\color{red}Verschluss_Ort}$                    | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 16                 | Fehler                | Bearbeitungsvermerk                                                                      | 58296           | Schloss                  | ${\color{gold}Schloss_W}$ <br> ${\color{red}Verschluss_Ort}$                    | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 17                 | Fehler                | Bearbeitungsvermerk                                                                      | 58334           | Schloss                  | ${\color{gold}Schloss_W}$ <br> ${\color{red}Verschluss_Ort}$                    | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 18                 | Fehler                | Bearbeitungsvermerk                                                                      | 64662           | Signal                   | ${\color{gold}Signal_Real_Aktiv_Schirm}$ <br> ${\color{red}Signalsystem}$       | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 19                 | Fehler                | Bearbeitungsvermerk                                                                      | 67071           | Signal                   | ${\color{gold}Signal_Real_Aktiv_Schirm}$ <br> ${\color{red}Signalsystem}$       | Planung                  | Start           | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 20                 | Fehler                | Bearbeitungsvermerk                                                                      | 98876           | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 21                 | Fehler                | Bearbeitungsvermerk                                                                      | 98940           | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 22                 | Fehler                | Bearbeitungsvermerk                                                                      | 99036           | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 23                 | Fehler                | Bearbeitungsvermerk                                                                      | 99084           | Anhang                   | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 24                 | Fehler                | Bearbeitungsvermerk                                                                      | 99299           | Aussenelementansteuerung | ${\color{gold}AEA_Allg}$ <br> ${\color{red}Aussenelementansteuerung_Art}$       | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 25                 | Fehler                | Bearbeitungsvermerk                                                                      | 99799           | Bedien_Anzeige_Element   | ${\color{gold}Bedien_Anzeige_Element_Allg}$ <br> ${\color{red}Taste}$           | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 26                 | Fehler                | Bearbeitungsvermerk                                                                      | 99871           | Bedien_Anzeige_Element   | ${\color{gold}Bedien_Anzeige_Element_Allg}$ <br> ${\color{red}Taste}$           | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 27                 | Fehler                | Bearbeitungsvermerk                                                                      | 99972           | Bedien_Anzeige_Element   | ${\color{gold}Bedien_Anzeige_Element_Allg}$ <br> ${\color{red}Taste}$           | Betrachtung              | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 28                 | Fehler                | Bearbeitungsvermerk                                                                      | 153969          | PZB_Element_Zuordnung    | ${\color{gold}PZB_Element_Zuordnung_Fstr}$ <br> ${\color{red}Wirksamkeit_Fstr}$ | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 29                 | Fehler                | Bearbeitungsvermerk                                                                      | 154765          | PZB_Element_Zuordnung    | ${\color{gold}PZB_Element_Zuordnung_Fstr}$ <br> ${\color{red}Wirksamkeit_Fstr}$ | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 34                 | Fehler                | Bearbeitungsvermerk                                                                      | 156915          | Schloss                  | ${\color{gold}Schloss_W}$ <br> ${\color{red}Verschluss_Ort}$                    | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 35                 | Fehler                | Bearbeitungsvermerk                                                                      | 156979          | Schloss                  | ${\color{gold}Schloss_W}$ <br> ${\color{red}Verschluss_Ort}$                    | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 36                 | Fehler                | Bearbeitungsvermerk                                                                      | 157017          | Schloss                  | ${\color{gold}Schloss_W}$ <br> ${\color{red}Verschluss_Ort}$                    | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 37                 | Fehler                | Bearbeitungsvermerk                                                                      | 163597          | Signal                   | ${\color{gold}Signal_Real_Aktiv_Schirm}$ <br> ${\color{red}Signalsystem}$       | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 38                 | Fehler                | Bearbeitungsvermerk                                                                      | 166062          | Signal                   | ${\color{gold}Signal_Real_Aktiv_Schirm}$ <br> ${\color{red}Signalsystem}$       | Planung                  | Ziel            | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 39                 | Fehler                | Bearbeitungsvermerk                                                                      | 334396          | Anhang_Dokumentation     | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      |                          |                 | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 40                 | Fehler                | Bearbeitungsvermerk                                                                      | 341540          | Anhang_Dokumentation     | ${\color{gold}Anhang_Allg}$ <br> ${\color{red}Anhang_Art}$                      |                          |                 | Fehlender Bearbeitungsvermerk bei Wert 'sonstige'.                                                                                                                                                       |
| 41..93             | Fehler                | Teilbereichsgrenze                                                                       |                 | Fstr_Fahrweg             | Bereich_Objekt_Teilbereich                                                      | Planung                  | Start           | Ungültige Teilbereichsgrenzen für LST-Objekt.                                                                                                                                                            |
| 94..100            | Fehler                | Teilbereichsgrenze                                                                       |                 | Gleis_Art                | Bereich_Objekt_Teilbereich                                                      | Betrachtung              | Start           | Ungültige Teilbereichsgrenzen für LST-Objekt.                                                                                                                                                            |
| 101..153           | Fehler                | Teilbereichsgrenze                                                                       |                 | Fstr_Fahrweg             | Bereich_Objekt_Teilbereich                                                      | Planung                  | Ziel            | Ungültige Teilbereichsgrenzen für LST-Objekt.                                                                                                                                                            |
| 154..160           | Fehler                | Teilbereichsgrenze                                                                       |                 | Gleis_Art                | Bereich_Objekt_Teilbereich                                                      | Betrachtung              | Ziel            | Ungültige Teilbereichsgrenzen für LST-Objekt.                                                                                                                                                            |
| 172                | Erfolg                | ${\color{gold}Koordinatensystem}$ <br> ${\color{red}Koordinate}$                         |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Instanzen von GEO_Punkt_Allg haben ein gültiges Koordinatensystem.}$ <br> ${\color{red}Die Verweise vom Punkt_Objekt auf den Geo_Punkt durch ID_Geo_Punkt_Berechnen sind plausibilisiert}$ |
| 173                | Erfolg                | ${\color{gold}Mehrfache Koordinatensystem}$ <br> ${\color{red}Koordinatensystem}$        |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Instanzen von GEO_Punkt_Allg haben ein konsistentes Koordinatensystem.}$ <br> ${\color{red}Instanzen von GEO_Punkt_Allg haben ein gültiges Koordinatensystem.}$                            |
| 174                | Erfolg                | Mehrfache Koordinatensystem                                                              |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Instanzen von GEO_Kante haben ein konsistentes Koordinatensystem.}$ <br> ${\color{red}Instanzen von GEO_Punkt_Allg haben ein konsistentes Koordinatensystem.}$                             |
| 175                | Erfolg                | ${\color{gold}Mehrfache Teilbereiche}$ <br> ${\color{red}Mehrfache Koordinatensystem}$   |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Teilbereichsgrenzen der LST-Objekte sind einzigartig.}$ <br> ${\color{red}Instanzen von GEO_Kante haben ein konsistentes Koordinatensystem.}$                                              |
| 176                | Erfolg                | ${\color{gold}Planungs-/Betrachtungsbereich}$ <br> ${\color{red}Mehrfache Teilbereiche}$ |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Objekte sind eindeutig im Planungs- oder Betrachtungsbereich verortet.}$ <br> ${\color{red}Teilbereichsgrenzen der LST-Objekte sind einzigartig.}$                                         |
| 177                | Erfolg                | ${\color{gold}Punktobjektabstand}$ <br> ${\color{red}Planungs-/Betrachtungsbereich}$     |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Der Punktobjektabstand aller LST-Objekte ist gültig.}$ <br> ${\color{red}Objekte sind eindeutig im Planungs- oder Betrachtungsbereich verortet.}$                                          |
| 178                | Erfolg                | ${\color{gold}TOP_Kante}$ <br> ${\color{red}Punktobjektabstand}$                         |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}TOP_Kanten und GEO_Kanten haben übereinstimmende Längen.}$ <br> ${\color{red}Der Punktobjektabstand aller LST-Objekte ist gültig.}$                                                        |
| 179                | Erfolg                | TOP_Kante                                                                                |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}TOP_Kanten haben eindeutige Endknoten.}$ <br> ${\color{red}TOP_Kanten und GEO_Kanten haben übereinstimmende Längen.}$                                                                      |
| 180                | Erfolg                | ${\color{gold}Ungültiger ID-Verweis}$ <br> ${\color{red}TOP_Kante}$                      |                 |                          |                                                                                 | Fachdaten                |                 | ${\color{gold}Verweise verweisen auf ein Objekt vom erwarteten Typ.}$ <br> ${\color{red}TOP_Kanten haben eindeutige Endknoten.}$                                                                         |
| ${\color{red}181}$ | ${\color{red}Erfolg}$ | ${\color{red}Ungültiger ID-Verweis}$                                                     | ${\color{red}}$ | ${\color{red}}$          | ${\color{red}}$                                                                 | ${\color{red}Fachdaten}$ | ${\color{red}}$ | ${\color{red}Verweise verweisen auf ein Objekt vom erwarteten Typ.}$                                                                                                                                     |

**Pull request merged**
